services:
  kafka:
    image: bitnami/kafka:3.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes                                            # 啟用 KRaft 模式
      - KAFKA_CFG_PROCESS_ROLES=controller,broker                         # 指定這個節點同時扮演 controller,broker(單點用)
      - KAFKA_CFG_NODE_ID=1                                               # 為這個 Kafka 節點指定一個唯一的節點 ID
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093                   # 定義「controller quorum」投票節點清單
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093   # 9092 接收 producer/consumer 的連線，9093 是KRaft 專用的 controller 通訊 port
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092             # 對內外宣告這個 broker 的位址
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER                    # 指定哪一個 listener 是 controller 的 (對應 9093)
      - ALLOW_PLAINTEXT_LISTENER=yes                                      # Bitnami 版 Kafka 的開關，允許使用 明文（非加密）通訊，否則會強制使用 SSL
    volumes:
      - kafka_data:/bitnami/kafka

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    restart: on-failure
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    restart: on-failure
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TOPIC_NAME=insurance_applications
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - kafka
      - producer

volumes:
  kafka_data:
